# do not touch this line
configVersion: 2

description: testing
keywords: ''
name: stocks

dataTypes:
  stockInfo:
    name: string
    symbol: string
    currentStockPrice: float
    changeInPercent: float
    dividendYield: float
    dividendPerShare: float

screens:
  - - stockInfo

widgets:
  stockInfo:
    display: label
    type: stockInfo
    key: name
    label: Stock:
      
